import { Button } from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import Layout from "../components/Layout";

export default function Home() {
  const router = useRouter();

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Button
          variant="contained"
          color="primary"
          onClick={() => router.push("/users")}
        >
          Users
        </Button>
      </main>
    </Layout>
  );
}
